#!/usr/bin/python

import time
import random
from datetime import datetime, timedelta
from influxdb_client import InfluxDBClient, Point, WriteOptions
from influxdb_client.client.write_api import WriteType

URL = "http://localhost:8086"
TOKEN = "YOUR_API_TOKEN"
ORG = "YOUR_ORG"
BUCKET = "YOUR_BUCKET"

TRUCK_ID_RANGE = [0,100]

# Array values:
#   1 - represents the lower limit it can have
#   2 - represents the lower upper it can have
#   3 - represent the last value it had

# In a case of [90,110,95], 90 is the lowest value it can have, 110 is the hiest value it can have and 95 is the last value it hade
POSSIBLE_COMPONENTS = {
    "cpu": {
        "temperature":       [313, 353, 330],               # Kelvin → (~40°C to 80°C)
        "power_consumption": [0, 300, 150],                 # Watts
        "current":           [0, 50, 25],                   # Amperes
        "impact_force":      [0, 20, 10]                    # Newtons
    },
    "proximity_sensor": {
        "distance":          [20, 180, 100],                # cm
        "power_consumption": [0, 3, 2],                     # Watts
        "current":           [0, 1, 0.5]                    # Amperes
    },
    "impact_sensor": {
        "impact_force":      [0, 10_000, 0],                # Newtons (0 represents no impact, 10k is a collision)
        "sensitivity":       [1, 100, 50],                  # arbitrary sensitivity scale (0-100)
        "power_consumption": [0, 5, 1]                      # Watts
    },
    "gps_chip": {
        "signal_strength":   [10, 55, 42],                  # dB-Hz (below 30 is poor, above 40 is good)
        "power_consumption": [0, 2, 0.8],                   # Watts
        "current":           [0, 0.5, 0.1],                 # Amperes
        "satellite_count":   [0, 24, 12]                    # number of satellites tracked
    },
    "accelerometer": {
        "acceleration":      [0, 40, 9.8],                  # m/s² (9.8 is resting gravity)
        "temperature":       [253, 343, 298],               # Kelvin (Ambient operating range)
        "power_consumption": [0, 1, 0.2]                    # Watts
    },
    "power_supply_unit": {
        "voltage":           [350, 450, 400],               # Volts (High voltage EV system)
        "current":           [0, 600, 120],                 # Amperes (High draw during heavy plowing)
        "power_output":      [0, 200_000, 48_000],          # Watts (Max 200kW / ~270HP)
        "temperature":       [293, 363, 330]                # Kelvin (Battery pack temp)
    },
    "temperature_sensor": {
        "temperature":       [243, 333, 293],               # Kelvin (-30°C to 60°C ambient)
        "power_consumption": [0, 0.5, 0.1]                  # Watts
    },
    "humidity_sensor": {
        "humidity":          [0, 100, 65],                  # %
        "power_consumption": [0, 0.5, 0.1]                  # Watts
    },
    "front_light": {
        "luminosity":        [0, 8_000, 0],                 # lumens (High powered LED work lights)
        "power_consumption": [0, 150, 2],                   # Watts (0 when off)
        "temperature":       [253, 353, 293]                # Kelvin (Heat generated by LEDs)
    },
    "engines": {
        "rpm":               [0, 12_000, 3_500],            # revolutions/min (Electric motors spin high)
        "temperature":       [293, 423, 350],               # Kelvin (Motor windings temp)
        "power_output":      [0, 150_000, 50_000],          # Watts
        "vibration":         [0, 10, 2]                     # arbitrary scale (10 is severe malfunction)
    },
    "breaks": {
        "temperature":       [273, 673, 300],               # Kelvin (Discs can get very hot under load)
        "pressure":          [0, 3000, 0],                  # psi (Hydraulic brake pressure)
        "response_time":     [0.05, 1.0, 0.2]               # seconds
    },
    "tires": {
        "temperature":       [263, 353, 310],               # Kelvin (Friction heat)
        "pressure":          [10_0000, 300_000, 220_000],   # Pascals (~14 to ~43 psi)
        "wear_level":        [0, 100, 15],                  # % wear
        "traction":          [1, 10, 8]                     # arbitrary scale (10=pavement, 1=mud/slip)
    }
}

POSSIBLE_ENVIRONMENT = {
    "temperature":  [283,303,293],          # Kelvin
    "humidity":     [30,90,60],             # %
    "luminosity":   [10_000,30_000,15_000]  # Lux
}

POSSIBLE_VEHICLE_DATA = {
    "velocity":     [6,3],      # m/s
    "connectivity": [100,50]    # ms
    # "odometer": [,] # m
    # "latitude": [,]
    # "longitude": [,]
}

POSSIBLE_BATTERY = {
    # "level":    []
    "current":  [200,200]  # Ampere
}

START_DATE = datetime(2024,1,1)
END_DATE = datetime(2024,12,30)

START_HOUR = time(6,0,0)
END_HOUR = time(17,0,0)

current_day = START_DATE





def main():
    while current_day <= END_DATE:
        work_start = datetime.combine(current_day.date(), START_HOUR)
        work_end = datetime.combine(current_day.date(), END_HOUR)

        current_time = work_start
        
        while current_time <= work_end:
            print(f"Processing: {current_time}")
            
            
            current_time += timedelta(seconds=1)
        
        current_day += timedelta(days=1)

if __name__ == "__main__":
    main()




